project:
  type: website
  # type: book
  output-dir: docs
  pre-render:
    - make process-eq-r
  render:
    - "*.qmd"
    - "!**/archive/"
  post-render:
    - make process-eq

execute:
  freeze: auto

website:
# book:
#   chapters:
#     - index.qmd
#     - about.qmd
#     - contact.qmd
#     - music.qmd
#     - part: posts.qmd
#       chapters:
#         - posts/2024-03-15-writing-temp/cheatsheet.qmd
#         - posts/2024-03-15-writing-temp/index.qmd
#     - part: "Writing"
#       chapters:
#         - posts/2024-03-18-bias-variance-decomposition/index.qmd
  google-analytics:
    tracking-id: "G-MBBG8HDJQG"
  title: "Matthew Bain"
  favicon: assets/favicon.jpg
  image: assets/favicon.jpg
  site-url: https://bainmatt.github.io
  repo-url: https://github.com/bainmatt/bainmatt.github.io
  open-graph: true
  search: true
  navbar:
    title: "Matthew Bain"
    background: "rgb(250, 250, 250)"
    left:
      # - href: index.qmd
      #   text: "Home"
      - href: about.qmd
        text: "About"
      - href: contact.qmd
        text: "Contact"
      - href: posts.qmd
        text: "Resources"
      - href: https://bainmatt.github.io/cv/cv_matthewbain.html
        text: "Résumé"
    right:
      - text: Misc
        menu:
        - href: music.qmd
          text: "Music"
        - icon: youtube
          text: "YouTube"
          href: https://www.youtube.com/@fujinai9/featured
      - icon: github
        href: https://github.com/bainmatt
      - icon: linkedin
        href: https://linkedin.com/in/bainmatt/
  page-footer:
    center:
      - href: https://bainmatt.github.io/
        text: bainmatt.github.io

format:
  html:
    theme: whale.scss  # default, cosmo, flatly
    css:
      - assets/layout.css
      - assets/styles.css
      
crossref:
  custom:
    - kind: float
      reference-prefix: Info
      key: inf