---
page-layout: full

format:
  html:
    toc: true
    toc_depth: 1
    toc-location: right
    toc-expand: false
    number_sections: false
---

::: {.banner}
::: {.centered}
<h1 style="letter-spacing: 2.5px;">Matthew Bain</h1>

---

Data scientist, machine learning expert, lover of statistics, and
part-time musician. Building interpretable, robust, responsible machine
learning applications.
:::
:::

```{r setup-r}
#| echo: false
library(reticulate)

source("src/r/cards.R")
```

```{python setup-py}
#| echo: false
import sys
import yaml
import pandas as pd

sys.path.append("src/python")
from cards import format_projects, sync_projects
```


```{python sync}
#| echo: false
#| eval: false

# 1. Synchronize records (run as needed)
sync_projects(
  src_path="~/Documents/career/resume/R/input/projects.csv",
  targ_path="data/projects.yaml",
  src_cols = [
    "link_text", "link", "tools", "short_summary"
  ],
  targ_cols=[
    "title", "name", "in_portfolio", "type",
    "img", "img_alt", "text"
  ]
)

```

```{python load}
#| echo: false

# 2. Load latest project records
with open("data/projects.yaml") as f:
  df_cards = pd.DataFrame(yaml.safe_load(f))

# 3. Format projects for cards
df_cards = format_projects(
  df=df_cards,
  default_img="icon-comp.jpg",
  default_img_alt="Photo of Mt. Fuji taken from the bullet train."
)

```

```{r process}
#| echo: false

# 4. Load cards into R
df_cards_r = pd2r(py$df_cards)

```

<!--
## Main sites

::: {.grid}

```{r}
#| echo: false
#| include: true
#| results: asis

print_cards(df_cards_r, keywords = c("blog"))

# add_card(
#   img = "childe-hassam-the-concord-meadow-comp.jpg",
#   name = "Data science blog", 
#   text = "I write a data science blog, \"Notes and numbers\",
#   link = "https://blog.matthewbain.net",
#   img_alt = "The Concord Meadow by Childe Hassam, public domain.",
#   link_text = "blog.matthewbain.net"
# )
  
```

:::
-->

## Packages

::: {.grid}

```{r}
#| echo: false
#| include: true
#| results: asis

print_cards(df_cards_r, keywords = c("r package"))
print_cards(df_cards_r, keywords = c("python package"))

```

:::

<!--
## Analyses

::: {.grid}

```{r}
#| echo: false
#| results: asis

print_cards(df_cards_r, keywords = c("analysis"))

```

:::
-->

## Misc.

::: {.grid}

```{r}
#| echo: false
#| results: asis

print_cards(df_cards_r, keywords = c("website", "dashboard", "app", "model"))

```

:::
