---
title: "Technical reports with R Markdown & Bookdown (A test of Quarto)"
subtitle: "Test subtitle"
abstract: |
  I provide markdown snippets for a variety of text environments and formats that can 
  be created with R Markdown and the Bookdown package. I focus on
  the elements that I find most useful for writing math.
author: "Matthew Bain"
date: "March 22, 2024"
notes: "This is a test of the notes section"
tags: 
  - Reference
thanks: "This is a test of the thanks section"
code-link: true
code-fold: show
crossrefs-hover: true
code-copy: hover
toc-expand: true
toc-location: left
footnotes-hover: true
number-sections: true
# self-contained-math: true

css: ../../generic-css.css
bibliography: ../../generic-bib.bib

toc: true
toc-depth: 2
fig-format: svg
cap-location: bottom
fig-align: left
code-line-numbers: false
citations-hover: true
format: html
---

The combination of R Markdown with functionality from the
[Bookdown](https://bookdown.org/) package and
[Distill](https://rstudio.github.io/distill/) web publishing format
provides a comprehensive set of tools for composing web documents. In
this high-level reference guide I cover the tools that I find most
useful for writing organized, easily referenced, math-heavy documents.
The examples are arbitrary, only meant to illustrate the syntax. The
[LaTeX](https://en.wikibooks.org/wiki/LaTeX/Mathematics) and
[markdown](https://www.markdownguide.org/) syntax are not explained. For
each example I provide the raw text followed by the rendered output.

# Definition, theorem, proof

Ah, the familiar math textbook refrain. Below is the Bookdown syntax for
definition, theorem, and proof environments, respectively.

#### Definition {.unnumbered}

``` latex
::: {#disjoint-sets-def .definition name="Disjoint sets"}
Two sets $A_1$ and $A_2$ are **disjoint** if their intersection 
$A_1 \cap A_2 = \emptyset$, where $\emptyset$ is the empty set. We say that
$n$ sets $A_1, A_2, ..., A_n$ are disjoint if $A_i \cap A_j = \emptyset$ 
for $i! = j$. 
:::
```

::: {#disjoint-sets-def .definition name="Disjoint sets"}
Two sets $A_1$ and $A_2$ are *disjoint* if their intersection
$A_1 \cap A_2 = \emptyset$, where $\emptyset$ is the empty set. We say
that $n$ sets $A_1, A_2, ..., A_n$ are disjoint if
$A_i \cap A_j = \emptyset$ for $i! = j$.
:::

#### Theorem {.unnumbered}

``` latex
::: {#pyth-thm .theorem name="Pythagorean theorem"}
Given a right triangle, if $c$ denotes the length of the hypotenuse and
$a$ and $b$ the lengths of the other two sides, then
$$a^2 + b^2 = c^2$$.
:::
```

::: {#pyth-thm .theorem name="Pythagorean theorem"}
Given a right triangle, if $c$ denotes the length of the hypotenuse and
$a$ and $b$ the lengths of the other two sides, then
$$a^2 + b^2 = c^2.$$
:::

<aside>Table 2.1 on
[this](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html)
page from *Authoring Books with R Markdown* lists all the other
available theorem environments and their respective keywords.</aside>

#### Proof {.unnumbered}

``` latex
::: {.proof name="Pythagorean theorem"}
Let $x, y$ be ...

... Thus, $$a^2 + b^2 = c^2,$$

as desired.

$$
\tag*{$\square$}
$$
:::
```

::: fig-border
:::

::: {.proof name="Pythagorean theorem"}
Let $x, y$ be ...

... Thus, $$a^2 + b^2 = c^2,$$

as desired.

$$
\tag*{$\square$}
$$
:::

::: fig-border
:::

#### Automatic numbering {.unnumbered}

The nice thing about Bookdown is that it will automatically number
definitions and theorems so that you can easily cross-reference them
later on (see the [Cross-references](#cross-references) section below).
Just replace the name following the `#` (`pyth-thm` in the example
below) with a unique label (containing no spaces) that will be
convenient to reference.

``` latex
::: {#cont-map-def .definition name="Continuous map"}
A continuous map is a continuous function between two topological spaces. 
:::
```

::: {#cont-map-def .definition name="Continuous map"}
A continuous map is a continuous function between two topological
spaces.
:::

<aside>Notice that definition's number was automatically incremented
from the previous definition.</aside>

# Assorted math examples {#math-elements}

Here is an assortment of LaTeX examples along with their output.

#### Brace annotation {.unnumbered}

``` latex
$$
\underbrace{\ln \left( \frac{5}{6} \right)}_{\simeq -0.1823}
< \overbrace{\exp \left(\frac{1}{2} \right)}^{\simeq 1.6487}
$$
```

$$
\underbrace{\ln \left( \frac{5}{6} \right)}_{\simeq -0.1823}
< \overbrace{\exp \left(\frac{1}{2} \right)}^{\simeq 1.6487}
$$

#### Brackets and braces {.unnumbered}

``` latex
$$
( a ), [ b ], \{ c \}, | d |, \| e \|,
\langle f \rangle, \lfloor g \rfloor,
\lceil h \rceil, \ulcorner i \urcorner,
/ j \backslash
$$
```

$$
( a ), [ b ], \{ c \}, | d |, \| e \|,
\langle f \rangle, \lfloor g \rfloor,
\lceil h \rceil, \ulcorner i \urcorner,
/ j \backslash
$$

``` latex
$$
( \big( \Big( \bigg( \Bigg(
$$
```

$$
( \big( \Big( \bigg( \Bigg(
$$

#### Fractions {.unnumbered}

``` latex
$$
\begin{equation}
    x = a_0 + \cfrac{1}{a_1 
            + \cfrac{1}{a_2 
            + \cfrac{1}{a_3 + \cfrac{1}{a_4} } } }
\end{equation}
$$
```

$$
\begin{equation}
    x = a_0 + \cfrac{1}{a_1 
            + \cfrac{1}{a_2 
            + \cfrac{1}{a_3 + \cfrac{1}{a_4} } } }
\end{equation}
$$

``` latex
$$
\frac{
\begin{array}[b]{r}
    \left( x_1 x_2 \right) \\
    \times 
    \left( x'_1 x'_2 \right)
\end{array}} {
\left( y_1y_2y_3y_4 \right) 
}
$$
```

<aside>The `\left(` / `\right)` command encloses its contents in big
brackets.</aside>

$$
\frac{
\begin{array}[b]{r}
    \left( x_1 x_2 \right) \\
    \times 
    \left( x'_1 x'_2 \right)
\end{array}} {
\left( y_1y_2y_3y_4 \right) 
}
$$

#### Calculus expressions {.unnumbered}

``` latex
$$
\int_0^\infty \mathrm{e}^{-x} ~ \mathrm{d}x
$$
```

$$
\int_0^\infty \mathrm{e}^{-x} ~ \mathrm{d}x
$$

``` latex
$$
\int\limits_a^b \sin(x) ~ \mathrm{d}x
$$
```

$$
\int\limits_a^b \sin(x) ~ \mathrm{d}x
$$

``` latex
$$
\sum_{
\substack{
    0<i<m \\
    0<j<n 
}} 
P(i,j)
$$
```

$$
\sum_{
\substack{
    0<i<m \\
    0<j<n 
}} 
P(i,j)
$$

#### Linear algebra expressions {.unnumbered}

``` latex
$$
\begin{matrix}
    a & b & c \\
    d & e & f \\
    g & h & i
\end{matrix}
$$
```

$$
\begin{matrix}
    a & b & c \\
    d & e & f \\
    g & h & i
\end{matrix}
$$

``` latex
$$
A_{m,n} = 
\begin{pmatrix}
    a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
    a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
    \vdots  & \vdots  & \ddots & \vdots  \\
    a_{m,1} & a_{m,2} & \cdots & a_{m,n} 
\end{pmatrix}
$$
```

$$
A_{m,n} = 
\begin{pmatrix}
    a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
    a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
    \vdots  & \vdots  & \ddots & \vdots  \\
    a_{m,1} & a_{m,2} & \cdots & a_{m,n} 
\end{pmatrix}
$$

``` latex
$$
X = 
\begin{bmatrix}
    x_1 & y_1 \\
    x_2 & y_2 \\
    x_3 & y_3
\end{bmatrix}
$$
```

$$
X = 
\begin{bmatrix}
    x_1 & y_1 \\
    x_2 & y_2 \\
    x_3 & y_3
\end{bmatrix}
$$

``` latex
$$
X 
= 
\left[\begin{matrix}
    a & b & c \\
    d & e & f \\
    g & h & i
\end{matrix}\right]
\left[\begin{matrix}
    y^{(1)} \\ 
    y^{(2)} \\
    y^{(3)}
\end{matrix}\right]
= 
\left[\begin{matrix}
    |                     & |                     & | \\
    y^{(1)} ~ \vec{x}_1   & y^{(2)} ~ \vec{x}_2   & y^{(3)} ~ \vec{x}_3 \\
    |                     & |                     & |
\end{matrix}\right]
\in \mathbb{R^3}
$$
```

<aside>The `~` symbol represents a whitespace character.</aside>

$$
\begin{align}
X 
& = 
\left[\begin{matrix}
    a & b & c \\
    d & e & f \\
    g & h & i
\end{matrix}\right]
\left[\begin{matrix}
    y^{(1)} \\ 
    y^{(2)} \\
    y^{(3)}
\end{matrix}\right] \\
& = 
\left[\begin{matrix}
    |                     & |                     & | \\
    y^{(1)} ~ \vec{x}_1   & y^{(2)} ~ \vec{x}_2   & y^{(3)} ~ \vec{x}_3 \\
    |                     & |                     & |
\end{matrix}\right]
\in \mathbb{R^3}
\end{align}
$$

```{=html}
<!--
& =
\left[\begin{matrix}
    - & x^{(1)} & - \\
    - & x^{(2)} & - \\
    - & x^{(3)} & -
\end{matrix}\right]
\left[\begin{matrix}
    y^{(1)} \\ 
    y^{(2)} \\
    y^{(3)}
\end{matrix}\right] \\
& =
\left[\begin{matrix}
    | & | & | \\
    \mathbf{x}_1 & \mathbf{x}_2 & \mathbf{x}_3 \\
    | & | & |
\end{matrix}\right]
\left[\begin{matrix}
    y^{(1)} \\ 
    y^{(2)} \\
    y^{(3)}
\end{matrix}\right] \\
!-->
```
#### Probability expressions {.unnumbered}

``` latex
$$
\left(\!
\begin{array}{c}
    n \\
    r
\end{array}
\!\right) 
= \frac{n!}{r!(n-r)!}
$$
```

$$
\left(\!
\begin{array}{c}
    n \\
    r
\end{array}
\!\right) 
= \frac{n!}{r!(n-r)!}
$$

``` latex
$$
\begin{equation} 
    \phi \left(x; \mu, \sigma \right) 
    = \frac{1}{\sqrt{2 \pi \sigma^2}} \exp 
    \left( - 
    \frac{\left(x - \mu\right)^2}{2 \sigma^2} 
    \right)
\end{equation}
$$
```

$$
\begin{equation} 
    \phi \left(x; \mu, \sigma \right) 
    = \frac{1}{\sqrt{2 \pi \sigma^2}} \exp 
    \left( - 
    \frac{\left(x - \mu\right)^2}{2 \sigma^2} 
    \right)
\end{equation}
$$

# Numbered equations

Unlike in pure LaTeX, in `bookdown` we must manually assign labels to
every line that should have a number. I do so for significant passages,
steps, and equations. Here is an example of a numbered equation:

``` latex
$$
\begin{equation} 
    \mathbb{P} \left(k\right) 
    = \binom{n}{k}
    p^k\left(1-p\right)^{n-k}
\end{equation} (\#eq:binom-eq)
$$
```

$$
\begin{equation} 
    \mathbb{P} \left(k\right) 
    = \binom{n}{k}
    p^k\left(1-p\right)^{n-k}
\end{equation} (\#eq:binom-eq)
$$

# Math blocks

#### Numbered blocks {.unnumbered}

Here is an example from the [Bookdown
documentation](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html).
It illustrates how to display a block of math with multiple lines that
share a single number and label. We use the LaTeX `split` environment to
split the number across lines and wrap it all in double dollar signs to
tell R to treat it as math rather than raw text. To give the block a
number we add an `(\#eq:<equation-label>)` after closing the split
environment with `\end{split}`. Just replace the text after the `\#eq:`
prefix with a memorable label of your choice.

```{=html}
<!--
Wrapping in `$$` rather than an `equation` environment comes at the cost
of in-editor syntax highlighting, but in exchange R Markdown will
display a preview of the rendered LaTeX.
!-->
```
``` latex
$$
\begin{split}
\mathrm{Var}(\hat{\beta}) & =\mathrm{Var}((X'X)^{-1}X'y) \\
    & = (X'X)^{-1}X'\mathrm{Var}(y)((X'X)^{-1}X')' \\
    & = (X'X)^{-1}X'\mathrm{Var}(y)X(X'X)^{-1}\\
    & = (X'X)^{-1}X'\sigma^{2}IX(X'X)^{-1} \\
    & = (X'X)^{-1}\sigma^{2}
\end{split}
(\#eq:var-beta)
$$
```

```{=html}
<!--
Notice that each aligned line begins with a single space. Some editors
automatically align the cursor to the start of the previous line -- R
Markdown doesn't always do this, so I like to add a single space to make
the LaTeX readable but still easy to type.
!-->
```
$$
\begin{split}
\mathrm{Var}(\hat{\beta}) & =\mathrm{Var}((X'X)^{-1}X'y) \\
    & = (X'X)^{-1}X'\mathrm{Var}(y)((X'X)^{-1}X')' \\
    & = (X'X)^{-1}X'\mathrm{Var}(y)X(X'X)^{-1} \\
    & = (X'X)^{-1}X'\sigma^{2}IX(X'X)^{-1} \\
    & = (X'X)^{-1}\sigma^{2}
\end{split}
(\#eq:var-beta)
$$

Some additional notes:

-   Each new line is preceded by a `\\` operator.
-   Each aligned expression begins with the `&` operator.

#### Numbered lines and inline notes {.unnumbered}

We can number lines individually by using the LaTeX `align` environment
and adding a unique `(\#eq:<equation-label>)` at the end of every line
that should have a number. Additionally, we can add in-line comments by
placing `&&` followed by `(<my LaTeX-formatted comment>)` at the end of
the line, before the number label. As with our use of the `&` operator
to align successive lines of math, the `&&` operator tells the LaTeX
compiler to align comments, but to do so to the right of the aligned
math.

``` latex
$$
\begin{align}
\sum_{i=1}^{n} \left( X_i - \overline{X} \right )
    & = \sum_{i=1}^{n}X_i - \sum_{i=1}^{n} \overline{X} 
        && \scriptstyle{ \left( \text{comment 1} \right)}
    (\#eq:sum-dev1) \\
    & = \sum_{i=1}^{n} X_i - n \overline{X}
        && \scriptstyle{ \left( 
        \begin{array}{c}
            \text{comment 2 has symbols: } \int_{a}^{b} 4 \pi r^2 \\
            \text{... and carries over to a second line.}
        \end{array}
        \right) }
    (\#eq:sum-dev2) \\
    & = \sum_{i=1}^{n}X_i - \sum_{i=1}^{n}X_i 
    (\#eq:sum-dev3) \\
    & = 0
\end{align}
$$
```

<aside>We use `scriptstyle` to make the inline text smaller. Other
custom display options are detailed
[here](https://www.overleaf.com/learn/latex/Display_style_in_math_mode)
(by *Overleaf*).</aside>

$$
\begin{align}
\sum_{i=1}^{n} \left( X_i - \overline{X} \right )
    & = \sum_{i=1}^{n}X_i - \sum_{i=1}^{n} \overline{X} 
        && \scriptstyle{ \left( \text{comment 1} \right)}
    (\#eq:sum-dev1) \\
    & = \sum_{i=1}^{n} X_i - n \overline{X}
        && \scriptstyle{ \left( 
        \begin{array}{c}
            \text{comment 2 has symbols: } \int_{a}^{b} 4 \pi r^2 \\
            \text{... and carries over to a second line.}
        \end{array}
        \right) }
    (\#eq:sum-dev2) \\
    & = \sum_{i=1}^{n}X_i - \sum_{i=1}^{n}X_i 
    (\#eq:sum-dev3) \\
    & = 0
\end{align}
$$

::: {#thm-line}
## Line

The equation of any straight line, called a linear equation, can be
written as:

$$
y = mx + b
$$
:::

See @thm-line.

Black-Scholes (@eq-black-scholes) is a mathematical model that seeks to
explain the behavior of financial derivatives, most commonly options:

$$
\frac{\partial \mathrm C}{ \partial \mathrm t } + \frac{1}{2}\sigma^{2} \mathrm S^{2}
\frac{\partial^{2} \mathrm C}{\partial \mathrm C^2}
  + \mathrm r \mathrm S \frac{\partial \mathrm C}{\partial \mathrm S}\ =
  \mathrm r \mathrm C 
$$ {#eq-black-scholes}
